### ISSUE TITLE
Gradelize the project

### ISSUE THREAD

**Issue by ghost** [GiraffaFS/giraffa#121]
Currently the project is on Maven which proves to be too verbose and too difficult for no reasons. Let's switch to Gradle

**Comment by ghost** [comment]
Working on it - the initial build works just fine: a bit more attention is needed to add findbugs and similar things.

**Comment by pjeli** [comment]
I did some additional work on top of @c0s's work. Was able to get a standalone and core build going successfully with all unit tests passing.

Had to make a couple subtle changes in order for everything to succeed. For example, had to modify TestXAttr in order to prevent it from deleting the "build" directory. Also had to move all the .proto files into src/main/proto.

We may want to close out #126.

**Comment by milandesai** [comment]
Nice! Quick note, we should also update the .gitignore file. In particular:
Remove "target/"
Add "build/"
Add ".gradle"

**Comment by pjeli** [comment]
Offline +1 from @shvachko. Committing.

**Comment by pjeli** [comment]
Committed as: 9c09f6f432b020683473fb0c8a518a7ecc6bd519.

**Comment by pjeli** [comment]
Just a side note for anyone using OSX and running into issues with IntelliJ while trying to import the project.

If you are getting a weird message saying something like "File not found; error=2", it is because your "protoc" executable is not visible to IntelliJ.

Make sure protoc is installed; you can install it easily via "brew install protobuf". Then make sure you link the protoc executable into /usr/bin like so: "sudo ln -s /usr/local/bin/protoc /usr/bin/protoc".
