### ISSUE TITLE
Move giraffa web to HttpServer2 and add Apache license to the package.

### ISSUE THREAD

**Issue by shvachko** [GiraffaFS/giraffa#157]
1. `GiraffaWebServer` should extend `HttpServer2` since `HttpServer` has been deprecated in Hadoop 2.7. This should fix deprecation warnings.
2. All classes in `org.apache.giraffa.web` package need to include Apache license.

**Comment by pjeli** [comment]
Taking this over. Makes sense to follow-up with this now that I just finished Issue #88.

**Comment by pjeli** [comment]
Okay submitted a Pull Request for this fix. Took a while to understand but I was unable to just "extend" to HttpServer2 because that class has the 'final' modifier making it so I can't subclass it in GiraffaWebServer. Therefore I had to result to encapsulation and a few other tricks since I could no longer load our "hbase-webapps/giraffa/" directory as part of the default context.

I was able to work around all this and even remove an entire class by making use of a new dependency and re-routing some of the JSP resource expectations from "/static/webjars" to just "/webjars".

It should all work; please test it for yourself.

**Comment by milandesai** [comment]
WebDemo ran successfully. +1

**Comment by milandesai** [comment]
Unfortunately though, after getting the standalone working, getting this error on the UI (not webdemo):
{code}
java.lang.IllegalStateException: No Java compiler available
    at org.apache.jasper.JspCompilationContext.createCompiler(JspCompilationContext.java:225)
    at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:560)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:299)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:315)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:265)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
{code}

**Comment by pjeli** [comment]
Committed as: 52fdc8e61eab611f208d8e69d155586331f57abc

Closing. Thanks.
