### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by shvachko** [GiraffaFS/giraffa#187]
Found a couple of typos:
- `HLMAdapter`: LeasManager
- `BlockManagementAgent`: remporary

If you see more add them here.

**Comment by weilintsaiWand** [comment]
I reviewed all java files and found:<br>
- `BlockManagementAgent`: seperate<br>
- `DirectoryTable`: objout, may be objOut?<br>
- `RowKeyBytes`:compatibality<br>

Please note that I only review those typo warnings reported by Intellij. Hence, I may 
miss some typos such as LeasManager since leas is a valid word to Intellij.

**Comment by shvachko** [comment]
Yes objOut is more consistent with our naming conventions.

**Comment by weilintsaiWand** [comment]
How about `groupname` in many files (should be groupName?). Other similar words are `mtime`, `atime`, `diskspaceQuota`, `blocksize`.

**Comment by weilintsaiWand** [comment]
Have a initial patch to fix `LeasManager/remporary/seperate/objout/compatibality`. 
Will update if we need update `groupname` and its similar words

**Comment by shvachko** [comment]
+1 on the patch. I can live with groupname for now. But let's pay more attention on naming conventions in the future.

**Comment by shvachko** [comment]
Could you assign this issue to yourself please.
