### ISSUE TITLE
Giraffa Web UI Failing

### ISSUE THREAD

**Issue by shvachko** [GiraffaFS/giraffa#88]
Original [issue 88](https://code.google.com/p/giraffa/issues/detail?id=88) created by shvachko on 2014-09-29T23:48:19.000Z:

localhost:40010 gives the following error:

Error 500
/hbase-webapps/giraffa/index.jsp(66,0) No tag &quot;genericpage&quot; defined in tag library imported with prefix &quot;t&quot;

**Comment by shvachko** [comment]
Comment [#1](https://code.google.com/p/giraffa/issues/detail?id=88#c1) originally posted by shvachko on 2014-09-29T23:48:42.000Z:

&lt;empty&gt;

**Comment by pjeli** [comment]
I have created an initial patch to get Giraffa WebUI working via 'WebDemoRunner' test class.
With my current work I can get the UI started but after that it fails to do any actual file browsing. It seems the main Giraffa, HBase, and NameNode pages work but functionality on the Giraffa page is broken.

For example I still cannot browse the Giraffa FileSystem.

I need to investigate further. @kpelykh, any chance I could ask you for help?

**Comment by pjeli** [comment]
Hey guys,

I was able to restore the majority of functionality back to the Giraffa WebUI. Turned out there was some issues in genericpage.tag file and we needed to upgrade JQuery. There are still some issues I am working on; for example the HDFS browser seems to still be busted but I suspect I know what's going on.

Here is a screenshot!
<img width="1433" alt="screen shot 2016-04-23 at 11 39 53 am" src="https://cloud.githubusercontent.com/assets/2126448/14763359/5e8b8eda-0948-11e6-91de-9ef4bd048228.png">

If someone could test out my branch (issue-88) and confirm that they can also get the WebUI to work I would greatly appreciate it!

**Comment by pjeli** [comment]
Okay guys!

I was able to restore full functionality of the Giraffa Web UI! Attaching screenshot showing the HDFS browser working again too.
<img width="1315" alt="screen shot 2016-04-23 at 4 03 19 pm" src="https://cloud.githubusercontent.com/assets/2126448/14764452/017d06b8-096d-11e6-8a8b-feba95e17d9e.png">

In my "issue-88" branch I have updated the README.md showing how to run the WebUI demo and made all necessary commits to make it work.

If someone could review / test my branch I would be grateful.

**Comment by shvachko** [comment]
Good job, Plamen. It works.
Found one bug: when I delete a file it does not refresh the page, so it looks like no-op, but it is actually deleted.
Can we also change "GRFS" to "Giraffa" in `Messages_en.properties`

**Comment by pjeli** [comment]
Awesome thanks!

I believe I know how to fix that. Just need to call refresh() after the delete function in filebrowser.js.

**Comment by pjeli** [comment]
Okay @shvachko the latest push to the issue-88 branch has fixes for what you mentioned and also fixed an un-expected side-effect of introducing the "execute" task which was causing "assemble" command to fail.

Let me know how the branch stands now.

**Comment by pjeli** [comment]
@shvachko has given an offline +1.

**Comment by pjeli** [comment]
This is now committed as df10a4461d50deadba4240d371281b57adce7335. Closing.
